implementation
smay1613/LTC-STL-Student pull request #15
Opened 2020-09-24 17:19 UTC by pro100Daim

MPanasenko 
functors task (1)

2020-09-24 19:11 UTC, smay1613 commented
Please fix pull request title

2020-09-24 19:13 UTC, smay1613 requested changes

2020-09-24 19:13 UTC, smay1613 commented on functors task (1)/student/include/impl.h
> +        case BeerBrand::HoeGaarden: beer = BeerBrand::Corona; break;
and what if we have 20+ beer brands? :)

2020-09-24 19:13 UTC, smay1613 commented on functors task (1)/student/include/impl.h
> +        default:
why do you need this empty "default"?
you can return "Oops" here

2020-09-25 09:38 UTC, smay1613 commented on functors task (1)/student/include/impl.h
> +            curr_beer = 0;
magic number

2020-09-25 09:38 UTC, smay1613 commented on functors task (1)/student/include/impl.h
> +        static int curr_beer {0};
don't use abbreviations

2020-09-25 09:48 UTC, pro100Daim commented on functors task (1)/student/include/impl.h
> +        case BeerBrand::HoeGaarden: beer = BeerBrand::Corona; break;
Thanks for reply!
Switch is removed.

2020-09-26 15:09 UTC, closed without merging